name: Run MATLAB Script
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
          products: >
            Deep_Learning_Toolbox
            Deep_Learning_Toolbox_Converter_for_ONNX_Model_Format
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: addpath("verasonics/tensorflow_to_matlab"), import_unet