name: Run MATLAB Script
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2020b
          products: >
            Deep_Learning_Toolbox
            Deep_Learning_Toolbox_Converter_for_ONNX_Model_Format
      - name: Run import_unet_2024b
        uses: matlab-actions/run-command@v2
        with:
          command: addpath("verasonics/tensorflow_to_matlab"), import_unet_2024b
      - name: Run import_cyclegan_2024b
        uses: matlab-actions/run-command@v2
        with:
          command: addpath("verasonics/tensorflow_to_matlab"), import_cyclegan_2024b
      - name: Run make_combined_model_2024b
        uses: matlab-actions/run-command@v2
        with:
          command: addpath("verasonics/tensorflow_to_matlab"), make_combined_model_2024b
      - name: Run test_DAGNetwork
        uses: matlab-actions/run-command@v2
        with:
          command: addpath("verasonics/external_process"), test_DAGNetwork